<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OD [
	<!ELEMENT OD (version , lexicon* , board+ , indirect_tables?, equipment_type+ , group+)>
	<!ELEMENT group (objectGroup* , object*)>
	<!ELEMENT objectGroup (documentation? , producer* , consumer* , count?)>
	<!ELEMENT documentation (RIDXCalculation? , brief+ , description* , values* , example* , remarks* , todo* , warning* , see* , author? , date?)>
	<!ELEMENT object (joinGroup? , producer* , consumer* , count? , documentation , subindex+)>
	<!ELEMENT subindex (crc* , documentation)>
	<!ELEMENT brief (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT author (#PCDATA)>
	<!ELEMENT date (#PCDATA)>
	<!ELEMENT remarks (#PCDATA)>
	<!ELEMENT warning (#PCDATA)>
	<!ELEMENT todo (#PCDATA)>
	<!ELEMENT see (#PCDATA)>
	<!ELEMENT values (#PCDATA)>
	<!ELEMENT example (#PCDATA)>
	<!ELEMENT RIDXCalculation (rule)*>
	<!ELEMENT crc (crcRule)>
	<!ELEMENT crcRule EMPTY>
	<!ELEMENT rule (#PCDATA)>
	<!ELEMENT board EMPTY>
	<!ELEMENT equipment_type (equipment_board_type*)>
	<!ELEMENT equipment_board_type EMPTY>
	<!ELEMENT word (#PCDATA)>
	<!ELEMENT meaning (#PCDATA)>
	<!ELEMENT lexicon (item)*>
	<!ELEMENT item (word , meaning+)>
	<!ELEMENT joinGroup EMPTY>
	<!ELEMENT count EMPTY>
	<!ELEMENT version EMPTY>
	<!ELEMENT producer EMPTY>
	<!ELEMENT consumer EMPTY>
	<!ELEMENT indirect_tables (table*)>
    <!ELEMENT table (documentation?,configuration+)>
    <!ELEMENT configuration (user+,addIndex+)>
    <!ELEMENT user EMPTY>
    <!ELEMENT addIndex EMPTY>

    <!ATTLIST table    tab_id ID    #REQUIRED>
    <!ATTLIST table    name   CDATA #REQUIRED>

    <!ATTLIST configuration    count_type   (prod|cons) #REQUIRED>

    <!ATTLIST user     bid      IDREF #REQUIRED>
    <!ATTLIST addIndex obj_id   IDREF #REQUIRED>

	<!ATTLIST subindex name CDATA #REQUIRED>
	<!ATTLIST subindex type CDATA #REQUIRED>
	<!ATTLIST subindex description CDATA #IMPLIED>
	<!ATTLIST subindex version CDATA #IMPLIED>
	<!ATTLIST subindex count CDATA "1">
	<!ATTLIST subindex obsolete (true | false) "false">

	<!ATTLIST count value CDATA #REQUIRED>
	<!ATTLIST version value CDATA #REQUIRED>
	<!ATTLIST joinGroup gid IDREF #REQUIRED>
	<!ATTLIST group name CDATA #REQUIRED>

	<!ATTLIST objectGroup gid ID #REQUIRED>
	<!ATTLIST objectGroup name CDATA #REQUIRED>

	<!ATTLIST crc index IDREF #IMPLIED>

	<!ATTLIST crcRule type (self | range | full | comfort | critical | misc | frange) #REQUIRED>
	<!ATTLIST crcRule start CDATA #IMPLIED>
	<!ATTLIST crcRule length CDATA #IMPLIED>
	<!ATTLIST crcRule fstart CDATA #IMPLIED>
	<!ATTLIST crcRule flength CDATA #IMPLIED>
	<!ATTLIST crcRule foreign IDREF #IMPLIED>

	<!ATTLIST consumer bid IDREF #REQUIRED>
	<!ATTLIST consumer count CDATA #REQUIRED>

	<!ATTLIST producer bid IDREF #REQUIRED>
	<!ATTLIST producer count CDATA #REQUIRED>

	<!ATTLIST board bid ID #REQUIRED>
	<!ATTLIST board name CDATA #REQUIRED>

	<!ATTLIST equipment_type etid ID #REQUIRED>
	<!ATTLIST equipment_type name CDATA #REQUIRED>

	<!ATTLIST equipment_board_type bid CDATA #REQUIRED>

	<!ATTLIST object name CDATA #REQUIRED>
	<!ATTLIST object start_index CDATA #REQUIRED>
	<!ATTLIST object virtual_start_index_offset CDATA "0">
	<!ATTLIST object id ID #REQUIRED>
	<!ATTLIST object constant (true | false) "false">
	<!ATTLIST object critical (true | false) #IMPLIED>
	<!ATTLIST object lastcheck CDATA #IMPLIED>
	<!ATTLIST object comfort (true | false) #IMPLIED>
	<!ATTLIST object misc (true | false) #IMPLIED>
	<!ATTLIST object elite  (true | false) "false">
	<!ATTLIST object a5     (true | false) "false">
	<!ATTLIST object innova (true | false) "false">
	<!ATTLIST object obsolete (true | false) "false">

	<!ATTLIST RIDXCalculation ref IDREF #IMPLIED>

	<!ATTLIST rule type (calc | comment | title) #IMPLIED>

	<!ATTLIST item id ID #REQUIRED>

	<!ATTLIST word acronym CDATA #IMPLIED>

	<!ENTITY TotalEquipmentCount "512">
	<!ENTITY SlotPerCMSI "832">
	<!ENTITY SlotPerECS "832">
	<!ENTITY SlotPerECSCMSI "1664">
	<!ENTITY BoardPerInet "1024">
	<!ENTITY SlotPerEquipment "13">
	<!ENTITY SlotPerEquipmentFull "15">
	<!ENTITY RepeaterPanelCount "128">
	<!ENTITY CMSIEquipmentCount "64">
	<!ENTITY ECSEquipmentCount "64">
	<!ENTITY ECSCMSIEquipmentCount "128">
	<!ENTITY MAXDevicesPerINET "32768">
	<!ENTITY MAXDevicesPerMBD "256">
	<!ENTITY MAXGroupPerINET "32768">
	<!ENTITY MAXZonePerINET "32768">
    <!ENTITY JBUSExtremaPerNetwork "16">
    <!ENTITY FAFPPerMGGCount "35">
    <!ENTITY MPSPerMGGCount "32">
    <!ENTITY DoubleMPSPerMGGCount "64">
    <!ENTITY M1NRPPerMGGCount "64">
    <!ENTITY FacetHashesPerMGGCount "70">
	<!ENTITY Indent "    ">
    <!ENTITY FunctionByEquipment "350">

	<!-- ENTITY ODTYPES SYSTEM "OD_types.xml"-->
	<!-- ELITE Const -->
	<!ENTITY EliteNetPanelCount     "8">
	<!ENTITY EliteDeviceCount       "512">
	<!ENTITY EliteNetDeviceCount    "2048">
	<!ENTITY EliteInputCount        "1024">
	<!ENTITY EliteNetInputCount     "4096">
	<!ENTITY EliteZoneCount         "512">
	<!ENTITY EliteNetZoneCount      "2048">
	<!ENTITY EliteFacetCount        "196">
	<!ENTITY EliteFunctionCount     "128">
	<!ENTITY EliteNetFunctionCount  "1024">
	<!ENTITY EliteGroupCount        "256">
	<!ENTITY EliteNetGroupCount     "2048">
	<!ENTITY EliteActivatorCount    "1024">
	<!ENTITY EliteTriggeredCount    "512">
	<!ENTITY EliteRepeaterPanelCount "32">
	<!ENTITY EliteSlotPerEquipment  "3">
	<!ENTITY EliteExtPerEquipment   "6">
	<!-- T-NET Const -->
	<!ENTITY T_NET_deviceTypeCount   "500">
	<!ENTITY T_NET_FaultTypeCount   "256">
	<!-- Apollo Const -->
	<!ENTITY Apollo_deviceTypeCount   "256">
]>
<?xml-stylesheet href="OD.xsl" type="text/xsl"?>
<OD>
  <version value="03150100"/>
  <lexicon>
    <item id="item_0001">
      <word>MBD</word>
      <meaning>Module Boucle DEFNet : controls up to 4 lines OR 2 loops. MBD Board will communicate with devices, using the DEFNet protocol</meaning>
    </item>
    <item id="item_0002">
      <word>MBT</word>
      <meaning>Module Boucle TNet : controls up to 6 lines OR 3 loops. MBT Board will communicate with devices, using the TNet protocol</meaning>
    </item>
    <item id="item_0003">
      <word>MGG</word>
      <meaning/>
    </item>
    <item id="item_0004">
      <word>M10R</word>
      <meaning/>
    </item>
    <item id="item_0005">
      <word>M8IO</word>
      <meaning/>
    </item>
    <item id="item_0006">
      <word>M4IO2R</word>
      <meaning/>
    </item>
    <item id="item_0007">
      <word>MSW</word>
      <meaning/>
    </item>
    <item id="item_0008">
      <word>AES</word>
      <meaning/>
    </item>
    <item id="item_0009">
      <word>EAES</word>
      <meaning/>
    </item>
    <item id="item_0010">
      <word>MEAES</word>
      <meaning/>
    </item>
    <item id="item_0011">
      <word>Device</word>
      <meaning>Element present on a MBD/MBT line or loop. This element can be a Point (ECS element) or a Deported Element (CMSI element)</meaning>
    </item>
    <item id="item_0012">
      <word>Device Port</word>
      <meaning/>
    </item>
    <item id="item_0013">
      <word>Slot</word>
      <meaning/>
    </item>
    <item id="item_0014">
      <word>Subslot</word>
      <meaning/>
    </item>
    <item id="item_0015">
      <word>PAS Index</word>
      <meaning/>
    </item>
    <item id="item_0016">
      <word acronym="RIDX">PAS Reduced Index</word>
      <meaning/>
    </item>
    <item id="item_0017">
      <word>PAS Sub-index</word>
      <meaning/>
    </item>
    <item id="item_0018">
      <word>PAS Object</word>
      <meaning/>
    </item>
    <item id="item_0019">
      <word acronym="OD">PAS Object Dictionary</word>
      <meaning/>
    </item>
    <item id="item_0020">
      <word>Activator element</word>
      <meaning/>
    </item>
    <item id="item_0021">
      <word>Triggered element</word>
      <meaning/>
    </item>
    <item id="item_0022">
      <word>Element in fault</word>
      <meaning/>
    </item>
    <item id="item_0023">
      <word>Element disabled</word>
      <meaning/>
    </item>
    <item id="item_0024">
      <word>Element in test</word>
      <meaning/>
    </item>
    <item id="item_0025">
      <word>MPE</word>
      <meaning>MPE is ELITE motherboard and achieving    majority of functions (Manage and interface the LCD display, Manage Power supply, Manage I/O interface, Manage option and extension board.</meaning>
    </item>
    <item id="item_0026">
      <word>MGER</word>
      <meaning>MGER is ELITE board. MGER is a communication module for the German market (FAT/FBF, alerting, transmission).</meaning>
    </item>
    <item id="item_0027">
      <word>ELOA</word>
      <meaning>ELOA is ELITE extention board. ELOA use one loop Apollo.</meaning>
    </item>
    <item id="item_0028">
      <word>ELOT</word>
      <meaning>ELOT is ELITE extention board. ELOT use one loop T-NET.</meaning>
    </item>
    <item id="item_0029">
      <word>ELIC</word>
      <meaning>ELIC is ELITE extention board. ELIC use 2 conventional lines.</meaning>
    </item>
    <item id="item_0030">
      <word>ELIS</word>
      <meaning>ELIS is ELITE extention board. ELIS use 2 sounder lines.</meaning>
    </item>
    <item id="item_0031">
      <word>EUGA</word>
      <meaning>EUGA is ELITE extention board. EUGA uses 1 sounder line and 1 relay.</meaning>
    </item>
   </lexicon>
  <board bid="board_0000" name="UNKNOWN"/>
  <board bid="board_0001" name="MBD"/>
  <board bid="board_0002" name="MBT"/>
  <board bid="board_0003" name="MGG"/>
  <board bid="board_0004" name="M10R"/>
  <board bid="board_0005" name="M8IO"/>
  <board bid="board_0006" name="MSW"/>
  <board bid="board_0007" name="MPS"/>
  <board bid="board_0008" name="M4IO2R"/>
  <board bid="board_0009" name="M4EVAC"/>
  <board bid="board_0010" name="M1NR_GENERIC"/>
  <board bid="board_0011" name="FAFP"/>
  <board bid="board_0012" name="TELE"/>
  <board bid="board_0013" name="MPE"/>
  <board bid="board_0014" name="MGER"/>
  <board bid="board_0015" name="ELOA"/>
  <board bid="board_0016" name="ELOT"/>
  <board bid="board_0017" name="ELIC"/>
  <board bid="board_0018" name="ELIS"/>
  <board bid="board_0019" name="BPS"/>
  <board bid="board_0020" name="FPM"/>
  <board bid="board_0021" name="M1NR_ETH_ETH"/>
  <board bid="board_0022" name="M1NR_CPL_ETH"/>
  <board bid="board_0023" name="M1NR_FO_ETH"/>
  <board bid="board_0024" name="M1NR_CPL_CPL"/>
  <board bid="board_0025" name="M1NR_CPL_FO"/>
  <board bid="board_0026" name="M1NR_FO_FO"/>
  <board bid="board_0027" name="EUGA"/>

	  <indirect_tables>
       <table tab_id="table_0000" name="RAW_Device">
           <documentation>
               <brief>Raw devices mapping</brief>
           </documentation>
           <configuration count_type="prod">
               <user bid="board_0001" /> <!-- MBD -->
               <user bid="board_0002" /> <!-- MBT -->
               <user bid="board_0004" /> <!-- M10R -->
               <user bid="board_0005" /> <!-- M8IO -->
               <user bid="board_0008" /> <!-- M4IO2R -->
               <user bid="board_0009" /> <!-- M4EVAC -->
               <user bid="board_0011" /> <!-- FAFP -->
               <addIndex obj_id="obj_0001"/>
           </configuration>
           <configuration count_type="prod">
               <user bid="board_0001" /> <!-- MBD -->
               <user bid="board_0002" /> <!-- MBT -->
               <addIndex obj_id="obj_0002" />
               <addIndex obj_id="obj_0003" />
           </configuration>
           <configuration count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0001"/>
           </configuration>
       </table>
       <table tab_id="table_0001" name="RAW_DeviceIO">
           <documentation>
               <brief>Raw devices IO mapping</brief>
           </documentation>
           <configuration  count_type="prod">
               <user bid="board_0001" /> <!-- MBD -->
               <user bid="board_0002" /> <!-- MBT -->
               <user bid="board_0004" /> <!-- M10R -->
               <user bid="board_0005" /> <!-- M8IO -->
               <user bid="board_0008" /> <!-- M4IO2R -->
               <user bid="board_0009" /> <!-- M4EVAC -->
               <user bid="board_0011" /> <!-- FAFP -->
               <addIndex obj_id="obj_0004"/>
           </configuration>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0004"/>
           </configuration>
       </table>
       <table tab_id="table_0002" name="Device">
           <documentation>
               <brief>Devices mapping</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0015"/>
               <addIndex obj_id="obj_0204"/>
           </configuration>
       </table>
       <table tab_id="table_0003" name="DeviceIO">
           <documentation>
               <brief>Devices IO mapping</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0018"/>
           </configuration>
       </table>
       <table tab_id="table_0004" name="Group">
           <documentation>
               <brief>Groups mapping</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0016"/>
           </configuration>
       </table>
       <table tab_id="table_0005" name="Zone">
           <documentation>
               <brief>Zones mapping</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0023"/>
           </configuration>
       </table>
       <table tab_id="table_0006" name="SafetyFunction">
           <documentation>
               <brief>Safety functions mapping</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0282"/>
           </configuration>
       </table>
       <table tab_id="table_0007" name="MSWState">
           <documentation>
               <brief>MSW Status</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <addIndex obj_id="obj_0109"/>
           </configuration>
       </table>
       <table tab_id="table_0008" name="NetworkState">
           <documentation>
               <brief>Network Status</brief>
           </documentation>
           <configuration  count_type="cons">
               <user bid="board_0003" /> <!-- MGG -->
               <user bid="board_0011" /> <!-- FAFP -->
               <user bid="board_0013" /> <!-- MPE -->
               <addIndex obj_id="obj_0011"/>
               <addIndex obj_id="obj_0022"/>
           </configuration>
       </table>
   </indirect_tables>
  <equipment_type etid="equipment_0001" name="A5">
      <equipment_board_type bid="board_0001" />
      <equipment_board_type bid="board_0002" />
      <equipment_board_type bid="board_0003" />
      <equipment_board_type bid="board_0004" />
      <equipment_board_type bid="board_0005" />
      <equipment_board_type bid="board_0006" />
      <equipment_board_type bid="board_0007" />
      <equipment_board_type bid="board_0008" />
      <equipment_board_type bid="board_0009" />
      <equipment_board_type bid="board_0010" />
      <equipment_board_type bid="board_0011" />
  </equipment_type>
  <equipment_type etid="equipment_0002" name="Elite">
      <equipment_board_type bid="board_0004" />
      <equipment_board_type bid="board_0005" />
      <equipment_board_type bid="board_0013" />
      <equipment_board_type bid="board_0014" />
      <equipment_board_type bid="board_0015" />
      <equipment_board_type bid="board_0016" />
      <equipment_board_type bid="board_0017" />
      <equipment_board_type bid="board_0018" />
      <equipment_board_type bid="board_0019" />
      <equipment_board_type bid="board_0020" />
      <equipment_board_type bid="board_0027" />
  </equipment_type>
  <group name="Generic objects">
      <objectGroup gid="grp_0005" name="board diagnostic_t">
          <documentation>
              <brief/>
          </documentation>
          <producer bid="board_0001" count="1"/>
          <producer bid="board_0002" count="1"/>
          <producer bid="board_0003" count="1"/>
          <producer bid="board_0004" count="1"/>
          <producer bid="board_0005" count="1"/>
          <producer bid="board_0006" count="1"/>
          <producer bid="board_0007" count="1"/>
          <producer bid="board_0008" count="1"/>
          <producer bid="board_0009" count="1"/>
          <producer bid="board_0010" count="1"/>
          <producer bid="board_0011" count="1"/>
          <producer bid="board_0013" count="1"/>
          <producer bid="board_0014" count="1"/>
          <producer bid="board_0015" count="1"/>
          <producer bid="board_0016" count="1"/>
          <producer bid="board_0017" count="1"/>
          <producer bid="board_0018" count="1"/>
          <producer bid="board_0019" count="1"/>
          <producer bid="board_0020" count="1"/>
          <producer bid="board_0027" count="1"/>
          <count value="1"/>
      </objectGroup>
      <objectGroup gid="grp_0006" name="Object to PDO list group_t">
          <documentation>
              <brief/>
          </documentation>
          <producer bid="board_0001" count="7"/>
          <producer bid="board_0002" count="7"/>
          <producer bid="board_0003" count="10"/>
          <producer bid="board_0004" count="2"/>
          <producer bid="board_0005" count="2"/>
          <producer bid="board_0006" count="0"/>
          <producer bid="board_0007" count="0"/>
          <producer bid="board_0008" count="0"/>
          <producer bid="board_0009" count="0"/>
          <producer bid="board_0010" count="0"/>
          <producer bid="board_0011" count="3"/>
          <producer bid="board_0013" count="0"/>
          <producer bid="board_0014" count="0"/>
          <producer bid="board_0015" count="0"/>
          <producer bid="board_0016" count="0"/>
          <producer bid="board_0017" count="0"/>
          <producer bid="board_0018" count="0"/>
          <producer bid="board_0019" count="0"/>
          <producer bid="board_0020" count="0"/>
          <producer bid="board_0027" count="0"/>
          <count value="65536"/>
      </objectGroup>
      <objectGroup gid="grp_0029" name="Object PDO trigger">
          <documentation>
              <brief/>
          </documentation>
          <producer bid="board_0001" count="1"/>
          <producer bid="board_0002" count="1"/>
          <producer bid="board_0003" count="1"/>
          <producer bid="board_0004" count="1"/>
          <producer bid="board_0005" count="1"/>
          <producer bid="board_0006" count="1"/>
          <producer bid="board_0007" count="1"/>
          <producer bid="board_0008" count="1"/>
          <producer bid="board_0009" count="1"/>
          <producer bid="board_0010" count="1"/>
          <producer bid="board_0011" count="1"/>
          <count value="256"/>
      </objectGroup>
      <objectGroup gid="grp_0040" name="Object Raw Clock Timespan">
          <documentation>
              <brief/>
          </documentation>
          <producer bid="board_0011" count="1"/>
          <consumer bid="board_0003" count="1"/>
          <count value="1"/>
      </objectGroup>
      <object id="obj_0012" name="tOD_BoardVersions_t" start_index="0x10" constant="true">
          <joinGroup gid="grp_0005"/>
          <documentation>
              <brief>Board versions</brief>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="xSoftwareVersion" type="type_0010" count="1" version="03150000">
              <documentation>
                  <brief>Software version embedded in board</brief>
              </documentation>
          </subindex>
          <subindex name="xPASVersion" type="type_0013" count="1" version="03150000">
              <documentation>
                  <brief>PAS version used on this board</brief>
              </documentation>
          </subindex>
          <subindex name="u8HardwareVersion" type="type_0001" count="1" version="03150000">
              <documentation>
                  <brief>Current board hardware PCB main version</brief>
              </documentation>
          </subindex>
          <subindex name="xManufacturedVersion" type="type_0264" count="1" version="03150000">
              <documentation>
                  <brief>Hardware version embedded in board</brief>
              </documentation>
          </subindex>
          <subindex name="xBoardType" type="type_0009" count="1" version="03150000">
              <documentation>
                  <brief>Which board type are we ? </brief>
              </documentation>
          </subindex>
      </object>
      <object id="obj_0013" name="tOD_InfoDiagBoard_t" start_index="0x11" constant="true">
          <joinGroup gid="grp_0005"/>
          <documentation>
              <brief>Board diagnostics informations</brief>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="xSerialNumber" type="type_0011" count="1" version="03150000">
              <documentation>
                  <brief>Board serial number</brief>
              </documentation>
          </subindex>
          <subindex name="u16Current" type="type_0003" count="1" version="03150000">
              <documentation>
                  <brief>Current consumption on digital power supply rail in mA</brief>
              </documentation>
          </subindex>
          <subindex name="u16VDigital" type="type_0003" count="1" version="03150000">
              <documentation>
                  <brief>Digital power supply rail voltage in mV</brief>
              </documentation>
          </subindex>
          <subindex name="s8BoardTemperature" type="type_0002" count="1" version="03150000">
              <documentation>
                  <brief>Current board temperature in celcius degree</brief>
              </documentation>
          </subindex>
          <subindex name="u8SI" type="type_0001" count="1" version="03150000">
              <documentation>
                  <brief>Ultima Installer Signature: SI </brief>
              </documentation>
          </subindex>

      </object>
      <object id="obj_0014" name="tOD_WhichPDOListUse_t" start_index="0xF0000">
          <joinGroup gid="grp_0006"/>
          <documentation>
              <brief>Link between index and PDO list</brief>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="bSendOnIntCh" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Use internal channel (Boards inside the equipment only)</brief>
              </documentation>
          </subindex>
          <subindex name="bSendOnFunCh" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Use functional list (all equipment from same function (CMSI/ECS/...))</brief>
              </documentation>
          </subindex>
          <subindex name="bSendOnGenCh" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Use general list (All equipments)</brief>
              </documentation>
          </subindex>
      </object>
      <object id="obj_0092" name="tOD_ObjPDOTrigger_t" start_index="0xE0000">
          <joinGroup gid="grp_0029"/>
          <documentation>
              <brief>Object PDO trigger</brief>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="bSyncOD" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Flag to synchronize Objects Dictionary : when a module received this subindex change, it must resend all its producted PDO</brief>
              </documentation>
          </subindex>
          <subindex name="bSyncSntpTime" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Flag to synchronize time from SNTP. Time-master MGG sends this trigger, in other MGG, force sntp synchronisation (unicast to MGG master and broadcast to MXX cards)</brief>
              </documentation>
          </subindex>
          <subindex name="bResetCmd" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Flag to reset the activation (command) state of MXX cards. When MXX received this trigger, it must resend command state to the board</brief>
              </documentation>
          </subindex>
          <subindex name="bIdentificationRequest" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Flag to ask a MGG to send indenfication SDO to board if sender is in its DDS</brief>
              </documentation>
          </subindex>
          <subindex name="bCRCRequest" type="type_0007" count="1" version="03150000">
              <documentation>
                  <brief>Flag to ask a MGG to broadcast its tOD_CRCEqChange_t object</brief>
              </documentation>
          </subindex>
      </object>
      <object id="obj_0121" name="tOD_RawClockTimespan_t" start_index="0xB10000">
          <joinGroup gid="grp_0040"/>
          <documentation>
              <brief>Shift between UTC time and real time</brief>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="s32RawClockTimespan" type="type_0006" count="1" version="03150000">
              <documentation>
                  <brief>signed value holds timespan between UTC time and local time in second unit.
				  Real time = UTC time + timespan</brief>
              </documentation>
          </subindex>
      </object>
      <object id="obj_0001" name="tOD_RAW_DeviceState_t" start_index="0x120000">
          <joinGroup gid="grp_0001"/>
		  <producer bid="board_0007" count="2"/>
		  <producer bid="board_0011" count="2"/>
          <documentation>
              <RIDXCalculation>
                  <rule>From 0000 to 7FFF, indexes concern CMSI type devices</rule>
                  <rule>From 8000 to FFFF, indexes concern ECS  type devices</rule>
                  <rule>Reduced indexes are defined in tDDS_DeviceInfo_t objects, field u16ReducedPASIndex</rule>
              </RIDXCalculation>
              <brief>Raw device state, produced by MBD/MBT/M8IO/M10R... boards</brief>
              <remarks>
                  Indexes are split into 2 groups :
                  &lt;dl&gt;
                  &lt;dt&gt; from &lt;em&gt;0000&lt;/em&gt; to &lt;em&gt;7FFF&lt;/em&gt; included&lt;/dt&gt;&lt;dd&gt;CMSI devices&lt;/dd&gt;
                  &lt;dt&gt; from &lt;em&gt;8000&lt;/em&gt; to &lt;em&gt;FFFF&lt;/em&gt; included&lt;/dt&gt;&lt;dd&gt;ECS devices&lt;/dd&gt;
                  &lt;/dl&gt;
                  This is a logical separation. Nothing request this split...
              </remarks>
          </documentation>
          <subindex name="sub0" type="type_0001" version="03150000">
              <documentation>
                  <brief>subindexes count</brief>
              </documentation>
          </subindex>
          <subindex name="xPort" type="type_0023" count="5" version="03150000">
              <documentation>