<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OD_types [
    <!ELEMENT OD_types      (type+)>
    <!ELEMENT type          (documentation,group*,(enum|field|alternative|bfield|fusion)*,regroupFields*)>
    <!ELEMENT documentation (brief?,description?,values*,examples?,remarks*,minimalValue?,maximalValue?,todo*,warning*,sees*,date?,author?)>
    <!ELEMENT field         (documentation,alternative*,bfield*,regroupFields*)>
    <!ELEMENT bfield        (documentation?)>
    <!ELEMENT enum          (documentation?)>
	<!ELEMENT brief         (#PCDATA)>
    <!ELEMENT description   (#PCDATA)>
    <!ELEMENT author        (#PCDATA)>
    <!ELEMENT date          (#PCDATA)>
    <!ELEMENT remarks       (#PCDATA)>
    <!ELEMENT warning       (#PCDATA)>
    <!ELEMENT todo          (#PCDATA)>
    <!ELEMENT sees          (#PCDATA)>
    <!ELEMENT values        (#PCDATA)>
    <!ELEMENT example       (#PCDATA)>
    <!ELEMENT examples      (example*)>
    <!ELEMENT case          (documentation?,bfield*)>
    <!ELEMENT minimalValue  (#PCDATA)>
    <!ELEMENT maximalValue  (#PCDATA)>
    <!ELEMENT group         (EMPTY|subgroup*)>
    <!ELEMENT subgroup      EMPTY>
    <!ELEMENT alternative   (case+)>
    <!ELEMENT regroupFields (rbfield+)>
    <!ELEMENT rbfield       EMPTY>
	<!ELEMENT fusion        (documentation?)>

    <!ATTLIST regroupFields name    CDATA #REQUIRED>
    <!ATTLIST rbfield       number  CDATA #REQUIRED>
	
    <!ATTLIST type  id       ID                       #REQUIRED>
    <!ATTLIST type  showValue   CDATA                    #IMPLIED>
    <!ATTLIST type  docValue    CDATA                    #IMPLIED>
    <!ATTLIST type  name     CDATA                       #REQUIRED>
    <!ATTLIST type  size     CDATA                       #REQUIRED>
    <!ATTLIST type  padding  CDATA                       #REQUIRED>
    <!ATTLIST type  cat      (enum|struct|value|alias|bitfield|fusion)   #REQUIRED>
    <!ATTLIST type  defined  (true|false)                #IMPLIED>
    <!ATTLIST type  display  (hex8|hex16|hex32|digit|text|raw|dot|dotinv|ascii) "raw">
    <!ATTLIST type  origin   IDREF                       #IMPLIED>
    <!ATTLIST type  deprecated  (true|false)             "false">
	<!ATTLIST type  foreign		CDATA                    #IMPLIED>
	<!ATTLIST type  fkey		CDATA                    #IMPLIED>
	<!ATTLIST type  fvalue		CDATA                    #IMPLIED>
	<!ATTLIST type  fprefix		CDATA                    #IMPLIED>

    <!ATTLIST enum  name     ID                          #REQUIRED>
    <!ATTLIST enum  value    CDATA                       #IMPLIED>
    <!ATTLIST enum  deprecated  (true|false)             "false">

    <!ATTLIST field name     CDATA                       #REQUIRED>
    <!ATTLIST field type     IDREF                       #REQUIRED>
    <!ATTLIST field count    CDATA                       "1">
    <!ATTLIST field bitfield (true|false)                #IMPLIED>
    <!ATTLIST field deprecated  (true|false)             "false">

    <!ATTLIST bfield name     CDATA                       #REQUIRED>
    <!ATTLIST bfield type     IDREF                       #IMPLIED>
    <!ATTLIST bfield size     CDATA                       #REQUIRED>
    <!ATTLIST bfield group    CDATA                       #IMPLIED>
    <!ATTLIST bfield subgroup CDATA                       #IMPLIED>
    <!ATTLIST bfield deprecated  (true|false)             "false">

	<!ATTLIST fusion origin     IDREF                     #REQUIRED>
	<!ATTLIST fusion offset     CDATA                     #REQUIRED>
	<!ATTLIST fusion name     	CDATA                     #REQUIRED>
	
    <!ATTLIST group name    CDATA #REQUIRED>
    <!ATTLIST group id      CDATA #REQUIRED>

    <!ATTLIST subgroup name    CDATA #REQUIRED>
    <!ATTLIST subgroup id      CDATA #REQUIRED>

    <!ATTLIST case name  CDATA #REQUIRED>
    <!ATTLIST case field CDATA #REQUIRED>
    <!ATTLIST case value CDATA #REQUIRED>
]>
<OD_types>
    <type id="RESERVED" name="Reserved" size="1" padding="1" cat="value" defined="true" >
        <documentation>
            <brief>Reserved bits definition</brief>
        </documentation>
    </type>

    <type id="type_0001" name="uint8" size="1" padding="1" cat="value" defined="true" >
        <documentation>
            <brief>basic uint8 value</brief>
        </documentation>
    </type>
    <type id="type_0002" name="sint8" size="1" padding="1" cat="value" defined="true" >
        <documentation>
            <brief>basic sint8 value</brief>
        </documentation>
    </type>
    <type id="type_0003" name="uint16" size="2" padding="2" cat="value" defined="true" >
        <documentation>
            <brief>basic uint16 value</brief>
        </documentation>
    </type>
    <type id="type_0004" name="sint16" size="2" padding="2" cat="value" defined="true" >
        <documentation>
            <brief>basic sint16 value</brief>
        </documentation>
    </type>
    <type id="type_0005" name="uint32" size="4" padding="4" cat="value" defined="true" >
        <documentation>
            <brief>basic uint32 value</brief>
        </documentation>
    </type>
    <type id="type_0006" name="sint32" size="4" padding="4" cat="value" defined="true" >
        <documentation>
            <brief>basic sint32 value</brief>
        </documentation>
    </type>
    <type id="type_0007" name="eSEF_BOOL" size="1" padding="1" cat="enum" defined="true" >
        <documentation>
            <brief>basic boolean type</brief>
        </documentation>
        <enum name="eSEF_FALSE" >
            <documentation>
                <brief>false boolean</brief>
            </documentation>
        </enum>
        <enum name="eSEF_TRUE" >
            <documentation>
                <brief>true boolean</brief>
            </documentation>
        </enum>
    </type>
    <type id="type_0008" name="eSEF_STATUS" size="1" padding="1" cat="value" defined="true" >
        <documentation>
            <brief>basic status type</brief>
        </documentation>
    </type>
    <type id="type_0009" name="ePAS_CARD" size="1" padding="1" cat="enum" foreign="OD.xml/board" fkey="bid" fvalue="name" fprefix="ePAS_CARD" >
        <documentation>
            <brief>INET boards list</brief>
        </documentation>
    </type>
    <type id="type_1000" name="eRIDXGroup" size="1" padding="1" cat="enum" foreign="OD.xml/indirect_tables/table" fkey="tab_id" fvalue="name" fprefix="eIND_LIST" >
        <documentation>
            <brief>INET boards list</brief>
        </documentation>
    </type>
    <type id="type_0110" name="tPASIndex" size="4" padding="4" origin="type_0005" cat="alias" defined="true" display="hex32">
        <documentation>
            <brief>Definition of a  PAS Index</brief>
        </documentation>
    </type>
    <type id="type_0111" name="tPASTypeIndex" size="2" padding="2" origin="type_0003" cat="alias" defined="true">
        <documentation>
            <brief>16 higher bits in a PAS Index</brief>
        </documentation>
    </type>
    <type id="type_0112" name="tPASReducedIndex" size="2" padding="2" origin="type_0003" cat="alias" defined="true" display="hex16">
        <documentation>
            <brief>16 lower bits in a PAS Index</brief>
        </documentation>
    </type>
    <type id="type_0113" name="tFilter_t" size="1" padding="1" cat="alias" origin="type_0001">
        <documentation>
            <brief>Number of event occurrence to wait before execute action or taking event into account</brief>
            <remarks>Maximum wait possible : 255 events</remarks>
        </documentation>
    </type>

    <type id="type_0125" name="eDDS_ThresholdValue_t" cat="alias" origin="type_0004" size="2" padding="2">
        <documentation>
            <brief>Define input threshold value</brief>
            <author>AGO</author>
        </documentation>
    </type>

    <type id="type_0121" name="tTimedFilterM_t" size="1" padding="1" cat="alias" origin="type_0001">
        <documentation>
            <brief>Time to wait (in minutes) before execute action or taking event into account</brief>
            <remarks>Maximum wait possible : 255' = 4h15&apos;</remarks>
        </documentation>
    </type>

    <type id="type_0122" name="tLongFilter_t" size="2" padding="2" cat="alias" origin="type_0003">
        <documentation>
            <brief>Number of events to wait before execute action or taking event into account</brief>
            <remarks>Maximum wait possible : 65535 events</remarks>
        </documentation>
    </type>
    <type id="type_0114" name="tLongTimedFilter_t" size="2" padding="2" cat="alias" origin="type_0003">
        <documentation>
            <brief>Time to wait (in seconds) before execute action or taking event into account</brief>
            <remarks>Maximum wait possible : 65 535s = 18h12&apos;15&quot;</remarks>
        </documentation>
    </type>
    <type id="type_0063" name="tSha_t" size="20" padding="1" cat="alias" origin="type_0001" display="hex16">
        <documentation>
            <brief>Result of Sha-1 computation</brief>
        </documentation>
    </type>
    <type id="type_0115" name="tCRC_t" size="2" padding="2" cat="alias" origin="type_0003" display="hex16">
        <documentation>
            <brief>CRC calculated with CRC-16-CCITT algorithm</brief>
        </documentation>
    </type>
    <type id="type_0010" name="tSoftwareVersion_t" cat="struct" size="4" padding="1">
        <documentation>
            <brief>General software version</brief>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <field name="u8Version" type="type_0001" count="1">
            <documentation>
            </documentation>
        </field>
        <field name="u8Revision" type="type_0001" count="1">
            <documentation>
            </documentation>
        </field>
        <field name="u8Index" type="type_0001" count="1">
            <documentation>
            </documentation>
        </field>
		<field name="u8Build" type="type_0001" count="1">
            <documentation>
            </documentation>
        </field>
    </type>
    <type id="type_0264" name="tManufacturedVersion_t" cat="struct" size="5" padding="1">
        <documentation>
            <brief>Manufactured version</brief>
        </documentation>
        <field name="u8PCBVersion" type="type_0001" count="1">
            <documentation>
            <brief>PCB Version</brief>
            </documentation>
        </field>
        <field name="u8ProductionFile" type="type_0001" count="1">
            <documentation>
            <brief>Letter which identifies the production file</brief>
    	    <remarks>ASCII code</remarks>
            </documentation>
        </field>
        <field name="u8Dash" type="type_0001" count="1">
            <documentation>
            <brief>Space allocated for the dash character</brief>
            <remarks>This one is optional</remarks>
	    <remarks>ASCII code</remarks>
            </documentation>
        </field>
        <field name="u8RetroActivity" type="type_0001" count="1">
            <documentation>
            <brief>Number which identifies a retroactive modification</brief>
            <remarks>This one is optional</remarks>
            </documentation>
        </field>
        <field name="u8Upgrade" type="type_0001" count="1">
            <documentation>
            <brief>Letter which identifies an upgrade on this PCB or a prototype</brief>
            <remarks>This one is optional</remarks>
    	    <remarks>ASCII code</remarks>
            </documentation>
        </field>
    </type>
    <type id="type_0011" name="tSerialNumber_t" cat="struct" size="9" padding="1">
        <documentation>
            <brief>type for board serial number</brief>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <field name="xSerialNumber" type="type_0001" count="9">
            <documentation>
            </documentation>
        </field>
    </type>

    <type id="type_0012" name="tSubslotPresences_t" cat="bitfield" size="1" padding="1">
        <documentation>
            <brief>fields use to determine if, in a slot, Subslots are Online/Offline</brief>
            <date>2014-10-29T10:33:55</date>
            <author>agosteau</author>
        </documentation>
        <bfield name="subslot 0 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 0 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 1 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 1 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 2 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 2 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 3 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 3 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 4 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 4 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 5 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 5 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 6 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 6 is online ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 7 is online" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 7 is online ? </brief>
            </documentation>
        </bfield>
    </type>
    <type id="type_0058" name="tSubslotFaults_t" cat="bitfield" size="1" padding="1">
        <documentation>
            <brief>fields use to determine if, in a slot, Subslots are OK or not</brief>
            <date>2014-10-29T10:33:55</date>
            <author>agosteau</author>
        </documentation>
        <bfield name="subslot 0 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 0 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 1 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 1 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 2 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 2 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 3 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 3 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 4 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 4 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 5 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 5 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 6 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 6 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
        <bfield name="subslot 7 is OK" size="1" type="type_0007">
            <documentation>
                <brief>is the subslot 7 is online/offline as expected ? </brief>
            </documentation>
        </bfield>
    </type>

    <type id="type_0013" name="tPASversion_t" cat="alias" size="4" padding="4" origin="type_0005" display="dotinv">
        <documentation>
            <brief>PAS version</brief>
            <description> </description>
            <author>agosteau</author>
        </documentation>
    </type>
    <type id="type_0014" name="tTimestamp_t" cat="alias" size="4" padding="4" origin="type_0005" >
        <documentation>
            <brief>event timestamps : seconds since 2010-01-01T00:00:00Z</brief>
            <description>
                Number of seconds since 2010-01-01T00:00:00 coded in 32bits
                @iexamples{
                02 Feb 2013 13:37:00 ==> 0x7CDBCF05,
                15 Jun 2025 18:21:39 ==> 0xA3677F06,
                07 Feb 2146 06:28:15 ==> 0xFFFFFFFF
                }
            </description>
            <remarks>Data is wrote in little endian mode</remarks>
            <remarks>The last date possible is the 2146-02-07T06:28:15</remarks>
            <date>2014-10-14T18:03:55</date>
        </documentation>
    </type>

    <type id="type_0015" name="eLedState_t" cat="enum" size="1" padding="1">
        <documentation>
            <brief>Possible LED states</brief>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <enum name="eLED_OFF" >
            <documentation>
                <brief>LED status is OFF (no light !)</brief>
                <date>2014-10-14T18:03:55</date>
            </documentation>
        </enum>
        <enum name="eLED_ON" >
            <documentation>
                <brief>LED status is ON (light is ON !)</brief>
            </documentation>
        </enum>
        <enum name="eLED_BLINK_SLOW" >
            <documentation>
                <brief>LED is bliking slowy (0.5Hz)</brief>
            </documentation>
        </enum>
        <enum name="eLED_BLINK_FAST" >
            <documentation>
                <brief>LED is bliking fastly (1.0Hz)</brief>
            </documentation>
        </enum>
    </type>
    <type id="type_0016" name="eBoardOperationnalState_t" cat="enum" size="1" padding="1">
        <documentation>
            <brief>Main board state</brief>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <enum name="eBOARD_OPERATIONNAL" >
            <documentation>
                <brief>Board is operational</brief>
            </documentation>
        </enum>
        <enum name="eBOARD_DOWNLOAD" >
            <documentation>
                <brief>Board is downloading its DDS</brief>
            </documentation>
        </enum>
    </type>

    <type id="type_0017" name="tBoardState_t" cat="bitfield" size="2" padding="2">
        <documentation>
            <brief>General board status, available on each modules</brief>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <bfield name="Operational State" size="2" type="type_0016">
            <documentation>
                <brief>Is the board downloading or not ? </brief>
            </documentation>
        </bfield>
        <bfield name="Red led status" size="2" type="type_0015">
            <documentation>
                <brief>Current red led status</brief>
                <description>
                    Normal red led status is ::@@type_0015::E1::name@@&lt;br&gt;
                    if red led status is ::@@type_0015::E2::name@@, then a system fault has been detected
                </description>
            </documentation>
        </bfield>
        <bfield name="Orange led status" size="2" type="type_0015">
            <documentation>
                <brief>Current orange led status</brief>
                <description>
                    Normal orange led status is ::@@type_0015::E1::name@@&lt;br&gt;
                    if orange led status is ::@@type_0015::E2::name@@, then a fault has been detected
                </description>
            </documentation>
        </bfield>
        <bfield name="Blue led status" size="2" type="type_0015">
            <documentation>
                <brief>Current blue led status</brief>
                <description>
                    Normal blue led status is ::@@type_0015::E3::name@@&lt;br&gt;
                    if blue led status is not ::@@type_0015::E3::name@@, then there is a problem with the board Operating system
                </description>
            </documentation>
        </bfield>
        <bfield name="DDS Missing" size="1" type="type_0007">
            <documentation>
                <brief>Boolean which indicates if DDS are invalid (or absent) or not</brief>
            </documentation>
        </bfield>
        <bfield name="DDS corrupted" size="1" type="type_0007">
            <documentation>
                <brief>Boolean which indicates if DDS in flash are compromised or not</brief>
                <description>The check is done by checking DDS CRC value</description>
                <remarks>If this field is ::@@type_0007::E2::name@@, then __@@type_0017::B7::name@@__ will be also ::@@type_0007::E2::name@@</remarks>
                <todo>DDS in flash ? in RAM ? </todo>
            </documentation>
        </bfield>
        <bfield name="Flash corrupted" size="1" type="type_0007">
            <documentation>
                <brief>Boolean which indicates if data in flash are compromised or not</brief>
                <description>The check is done by checking CRC value</description>
            </documentation>
        </bfield>
        <bfield name="Temperature Fault" size="1" type="type_0007">
            <documentation>
                <brief>Boolean is true if there is an issue with board temperature</brief>
            </documentation>
        </bfield>
        <bfield name="Supply current fault" size="1">
            <documentation>
                <brief>Boolean is true if there is an issue with board supplied current</brief>
            </documentation>
        </bfield>
        <bfield name="Sequencing fault" size="1" type="type_0007">
            <documentation>
                <brief>Boolean which indicates if one or several tasks are not running</brief>
            </documentation>
        </bfield>
        <bfield name="WD Reset" size="1" type="type_0007">
            <documentation>
                <brief>Boolean which indicates if a WD reset occured or not</brief>
            </documentation>
        </bfield>
        <bfield name="Is disable" size="1" type="type_0007">
            <documentation>
                <brief>Module has been disabled</brief>
            </documentation>
        </bfield>
        <regroupFields name="Functional fault">
            <rbfield number="5"/>
            <rbfield number="6"/>
            <rbfield number="7"/>
            <rbfield number="10"/>
            <rbfield number="11"/>
        </regroupFields>
        <regroupFields name="System fault">
            <rbfield number="6"/>
            <rbfield number="7"/>
            <rbfield number="10"/>
            <rbfield number="11"/>
        </regroupFields>
        <regroupFields name="Fault">
            <rbfield number="5"/>
            <rbfield number="6"/>
            <rbfield number="7"/>
            <rbfield number="8"/>
            <rbfield number="9"/>
            <rbfield number="10"/>
        </regroupFields>
        <regroupFields name="DDS Fault">
            <rbfield number="5"/>
            <rbfield number="6"/>
        </regroupFields>
    </type>
    <type id="type_0018" name="eDeviceState_t" cat="enum" size="1" padding="1">
        <documentation>
            <brief>Device state</brief>
            <description>
                Faults start with @@type_0018::E3::name@@
                Section integrity start with @@type_0018::E5::name@@
            </description>
            <date>2014-10-14T18:03:55</date>
        </documentation>
        <enum name="eDEVICE_STANDBY" >
            <documentation>
                <brief>Device does not have any fault, and is ready to work.</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_MISSING" >
            <documentation>
                <brief>Device is missing</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_BAD_ANSWER" >
            <documentation>
                <brief>Device give us a bad answer</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_BAD_ID1" >
            <documentation>
                <brief>Device has a bad first id</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_BAD_ID2" >
            <documentation>
                <brief>Device has a bad second id</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_BAD_SIGNATURE" >
            <documentation>
                <brief>Device has a bad signature</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_INTEGRITY" >
            <documentation>
                <brief>Device answer, but not to the integrity request</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_RAM" >
            <documentation>
                <brief>Device has reported a RAM fault (integrity check failed)</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_EEPROM" >
            <documentation>
                <brief>Device has reported an EEPROM fault (integrity check failed)</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_CRC_DDS" >
            <documentation>
                <brief>Device has reported an integrity fault on its DDS</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SETTING_FAIL" >
            <documentation>
                <brief>Device failed to be configured</brief>
                <remarks>This is an integrity fault</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_CRC_FACTORY" >
            <documentation>
                <remarks>This is an integrity fault</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_OC" >
            <documentation>
                <brief>Device gave us an Open-circuit fault</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SC" >
            <documentation>
                <brief>Device gave us an Short-circuit fault</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SENSOR" >
            <documentation>
                <brief>Device has reported that its sensor is in fault</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_REARM" >
            <documentation>
                <brief>Device failed to be rearmed</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SYSTEM_FAULT" >
            <documentation>
                <brief>Device have a system fault</brief>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_RADIO_DIALOG" >
            <documentation>
                <remarks>Radio devices  only</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_RADIO_BATTERY" >
            <documentation>
                <remarks>Radio devices  only</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_RADIO_RANGE_LIMIT" >
            <documentation>
                <remarks>Radio devices  only</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_RADIO_OIR_SYSTEM" >
            <documentation>
                <remarks>Radio devices  only</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SAME_ADDRESS" >
            <documentation>
                <remarks>Radio devices  only</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_CONFIG" >
            <documentation>
                <remarks>Radio devices  only</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_SETTING" >
            <documentation>
                <remarks>Radio devices  only</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_UPDATE_TIME" >
            <documentation>
                <remarks>Radio devices  only</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_UNCALIBRATED" >
            <documentation>
                <remarks>Radio devices  only</remarks>
                <todo>Don't know what to do with that</todo>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_BEAM_CUT" >
            <documentation>
                <remarks>Beam detector</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_DAZZLE" >
            <documentation>
                <remarks>Beam detector</remarks>
            </documentation>
        </enum>
        <enum name="eDEVICE_FAULT_KEY_OUT" >
            <documentation>
                <remarks>Beam detector</remarks>